Remote MQTT endpoint CA certificate file should be optional
eclipse-kanto/suite-connector pull request #37
Opened 2022-08-05 12:07 UTC by antonia-avramova

[#34 ] Remote MQTT endpoint CA certificate file should be optional

Remove default value of CA certificate file

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2022-08-16 10:10 UTC, hristobojilov commented on config/connections.go
> +	noCertificates := true
Do  not hard-code logic by using flags.

2022-08-16 10:11 UTC, hristobojilov commented on config/connections.go
> -	if len(tlsConfig.Certificates) == 0 {
Do not alter this code block

2022-08-16 10:12 UTC, hristobojilov commented on config/connections.go
> +	cert := tls.Certificate{}
It is possible to use certificates without TLS enabled.

2022-08-16 10:17 UTC, hristobojilov commented on config/connections.go
> +	case "wss", "ssl", "tls", "mqtts", "mqtt+ssl", "tcps":
Duplicate code

2022-08-16 10:23 UTC, hristobojilov requested changes
Please fix these issues

2022-08-17 06:26 UTC, hristobojilov approved these changes

2022-08-17 07:19 UTC, e-grigorov requested changes

2022-08-17 07:19 UTC, e-grigorov commented on config/settings.go
> +			return errors.Errorf("failed to read CA certificate file '%s'", settings.CACert)
This error message is not correct. That's the case when we have secure endpoint without CA certificates.

2022-08-17 08:38 UTC, e-grigorov approved these changes

2022-08-17 08:40 UTC, merged