Switch to the last Watermill version
eclipse-kanto/suite-connector pull request #93
Opened 2023-08-17 07:31 UTC by daniel-milchev

[#61] Switched to the latest version of watermill.
Signed-off-by: Daniel Milchev fixed-term.daniel.milchev@bosch.io

2023-08-18 07:05 UTC, dimitar-dimitrow requested changes

2023-08-18 07:05 UTC, dimitar-dimitrow commented on go.mod
> +	github.com/cenkalti/backoff/v3 v3.2.2
The cenkalti/backoff/v3 version has increased also, but it is not updated in the NOTICE file. Use _go version -m <suite-connector-binary>_ to list the versions of the build dependencies that goes in the binary and update them in the NOTICE file.

2023-08-18 07:50 UTC, k-gostev commented
Did anyone test if the build is working with go 1.17.0? Yocto recipes should be verified as well before merging.

2023-08-18 10:19 UTC, hristobojilov commented
This build now requires go 1.20 but yocto should build successfully.

2023-08-18 10:38 UTC, hristobojilov requested changes

2023-08-18 10:38 UTC, hristobojilov commented on go.mod
> -	github.com/ThreeDotsLabs/watermill v1.1.1
Update go version used to 1.20

2023-08-21 07:35 UTC, hristobojilov approved these changes

2023-08-21 08:10 UTC, dimitar-dimitrow approved these changes

2023-08-21 08:12 UTC, merged